#ifndef __AARCH64_SYSCALL_INTERFACE__
#define __AARCH64_SYSCALL_INTERFACE__

#define SYSCALL_SCHEDULING_YIELD		   0
#define SYSCALL_SCHEDULING_SLEEP		   1

#define SYSCALL_MEMORY_ALLOC			1000


#define SYSCALL_DEVICE_ALLOC			2000


#define SYSCALL_INTERRUPT_ATTACH		3000
#define SYSCALL_INTERRUPT_COMPLETE		3001


#endif
