#ifndef __AARCH64_SYSCALL_INTERFACE__
#define __AARCH64_SYSCALL_INTERFACE__

#define SYSCALL_SCHEDULING_YIELD		   0U
#define SYSCALL_SCHEDULING_SLEEP		   1U

#define SYSCALL_MEMORY_ALLOC			1000U


#define SYSCALL_DEVICE_ALLOC			2000U


#define SYSCALL_

#endif
