#ifndef __AARCH64_SYSCALL_INTERFACE__
#define __AARCH64_SYSCALL_INTERFACE__

#define SYSCALL_SCHEDULING_YIELD		   0
#define SYSCALL_SCHEDULING_SLEEP		   1
#define SYSCALL_SCHEDULING_THREAD_CREATE   2
#define SYSCALL_SCHEDULING_THREAD_ID_GET   3

#define SYSCALL_MEMORY_ALLOC			1000


#define SYSCALL_DEVICE_ALLOC			2000


#define SYSCALL_INTERRUPT_ATTACH		3000
#define SYSCALL_INTERRUPT_COMPLETE		3001


#define SYSCALL_IPC_PIPE_CREATE			4000
#define SYSCALL_IPC_PIPE_ID_GET			4001
#define SYSCALL_IPC_PIPE_WRITE			4002
#define SYSCALL_IPC_PIPE_READ			4003
#define SYSCALL_IPC_PIPE_INFO_GET		4004


#endif
